server:
  port: 18086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos.com
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.182.128
  elasticsearch:
    rest:
      uris: http://192.168.182.128:9200
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 192.168.182.128
    username: fengge
    password: fengge
    virtual-host: /fengge
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual
feign:
  sentinel:
    enabled: true


