server:
  port: 18091
spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos.com
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

  redis:
    host: 192.168.182.128
  rabbitmq:
    host: 192.168.182.128
    username: fengge
    password: fengge
    virtual-host: /fengge
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
feign:
  sentinel:
    enabled: true
auth:
  jwt:
    pubKeyPath: D:\\develop\\ideaworkspace\\gmall-1010\\rsa\\rsa.pub
    expire: 30
    cookieName: GMALL_TOKEN
    userKeyName: user-key




