server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos.com
    gateway:
      routes:
        - id: pms-route
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: sms-route
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: oms-route
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: ums-route
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: wms-route
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: index-route
          uri: lb://index-service
          predicates:
            - Path=/index/**
        - id: item-route
          uri: lb://item-service
          predicates:
            - Path=/item/**
        - id: msg-route
          uri: lb://msg-service
          predicates:
            - Path=/msg/**
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: cart-route
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
        - id: order-route
          uri: lb://order-service
          predicates:
            - Path=/order/**
      x-forwarded:
        host-enabled: true

auth:
  jwt:
    pubKeyPath: D:\\develop\\ideaworkspace\\gmall-1010\\rsa\\rsa.pub
    cookieName: GMALL_TOKEN