server:
  port: 18088
spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos.com
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.182.128

feign:
  sentinel:
    enabled: true

