server:
  port: 18084
spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos.com
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  datasource:
    url: jdbc:mysql://192.168.182.128:3306/guli_ums
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: 192.168.182.128
  rabbitmq:
    host: 192.168.182.128
    username: fengge
    password: fengge
    virtual-host: /fengge
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath*:mapper/ums/**/*.xml
  type-aliases-package: com.atguigu.gmall.ums.entity
  global-config:
    db-config:
      id-type: auto
